linters:
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            - "cel.dev/expr"
            - "cloud.google.com/go/compute/metadata"
            - "github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp"
            - "github.com/cespare/xxhash/v2"
            - "github.com/cncf/xds/go"
            - "github.com/envoyproxy/go-control-plane"
            - "github.com/envoyproxy/go-control-plane/envoy"
            - "github.com/envoyproxy/go-control-plane/ratelimit"
            - "github.com/envoyproxy/protoc-gen-validate"
            - "github.com/go-jose/go-jose/v4"
            - "github.com/go-logr/logr"
            - "github.com/go-logr/stdr"
            - "github.com/golang-jwt/jwt/v5"
            - "github.com/golang/glog"
            - "github.com/golang/protobuf"
            - "github.com/google/go-cmp"
            - "github.com/google/uuid"
            - "github.com/prometheus/client_golang"
            - "github.com/prometheus/client_model"
            - "github.com/prometheus/common"
            - "github.com/prometheus/procfs"
            - "github.com/planetscale/vtprotobuf"
            - "github.com/spiffe/go-spiffe/v2"
            - "go.opentelemetry.io/auto/sdk"
            - "go.opentelemetry.io/contrib/detectors/gcp"
            - "go.opentelemetry.io/otel"
            - "go.opentelemetry.io/otel/metric"
            - "go.opentelemetry.io/otel/sdk"
            - "go.opentelemetry.io/otel/sdk/metric"
            - "go.opentelemetry.io/otel/trace"
            - "golang.org/x/crypto"
            - "golang.org/x/crypto/bcrypt"
            - "golang.org/x/mod"
            - "golang.org/x/net"
            - "golang.org/x/oauth2"
            - "golang.org/x/sync"
            - "golang.org/x/sys"
            - "golang.org/x/term"
            - "golang.org/x/text"
            - "golang.org/x/tools"
            - "gonum.org/v1/gonum"
            - "google.golang.org/genproto"
            - "google.golang.org/genproto/googleapis/api"
            - "google.golang.org/genproto/googleapis/rpc"
            - "google.golang.org/grpc"
            - "google.golang.org/grpc/codes"
            - "google.golang.org/grpc/metadata"
            - "google.golang.org/grpc/status"
            - "google.golang.org/protobuf"
            - "hostingmaster.io/hm-lib"
            - "hostingmaster.io/hm-lib/audit"
            - "hostingmaster.io/hm-lib/crypto"
            - "hostingmaster.io/hm-lib/grpc"
            - "hostingmaster.io/hm-lib/jwt"
            - "hostingmaster.io/hm-lib/rate"
            - "hostingmaster.io/hm-lib/ratelimit"
            - "hostingmaster.io/hm-lib/templates"
            - "hostingmaster.io/hm-lib/tenants"
    varnamelen:
      ignore-decls:
        - "v jwt.Validator"
